title: 'Fundacja eF Kropka'
default_lang: pl
author:
  name: 'Joanna Å»elek'
  email: mcstando@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
